import { Tool } from '@/types';

export const tools: Tool[] = [
  // Phase 1 - Core MVP Tools
  {
    id: 'status',
    title: 'Server Status',
    description: 'Check if a Minecraft server is online, view players, version, and MOTD',
    icon: 'server',
    href: '/tools/status',
    category: 'server',
    phase: 1,
  },
  {
    id: 'ip',
    title: 'IP & Port Finder',
    description: 'Resolve server IP address, port, and SRV records',
    icon: 'network-wired',
    href: '/tools/ip',
    category: 'server',
    phase: 1,
  },
  {
    id: 'version',
    title: 'Version Checker',
    description: 'Check Minecraft server version and protocol number',
    icon: 'code-branch',
    href: '/tools/version',
    category: 'server',
    phase: 1,
  },
  {
    id: 'motd',
    title: 'MOTD Editor',
    description: 'Create and preview server MOTD with color codes',
    icon: 'palette',
    href: '/tools/motd',
    category: 'server',
    phase: 1,
  },
  {
    id: 'uuid',
    title: 'UUID & Skin Lookup',
    description: 'Find player UUID and view their Minecraft skin',
    icon: 'user',
    href: '/tools/uuid',
    category: 'player',
    phase: 1,
  },
  {
    id: 'enchants',
    title: 'Enchantments Guide',
    description: 'Get recommended enchantments for your items',
    icon: 'sparkles',
    href: '/tools/enchants',
    category: 'utility',
    phase: 1,
  },
  {
    id: 'skin',
    title: 'Player Skin Viewer',
    description: 'Preview Minecraft player skins in 2D and 3D',
    icon: 'image',
    href: '/tools/skin',
    category: 'player',
    phase: 1,
  },
  
  // Phase 2 - Advanced Tools
  {
    id: 'playergraph',
    title: 'Player Graph',
    description: 'View server player count over time',
    icon: 'chart-line',
    href: '/tools/playergraph',
    category: 'server',
    phase: 2,
  },
  {
    id: 'ping',
    title: 'Ping Test',
    description: 'Test server latency from multiple regions',
    icon: 'stopwatch',
    href: '/tools/ping',
    category: 'server',
    phase: 2,
  },
  {
    id: 'whitelist',
    title: 'Whitelist/Ban Checker',
    description: 'Check if a player is whitelisted or banned',
    icon: 'shield-halved',
    href: '/tools/whitelist',
    category: 'server',
    phase: 2,
  },
  {
    id: 'versioncmp',
    title: 'Version Comparison',
    description: 'Compare Minecraft versions across servers',
    icon: 'code-compare',
    href: '/tools/versioncmp',
    category: 'server',
    phase: 2,
  },
  {
    id: 'username',
    title: 'Username Checker',
    description: 'Check if a Minecraft username is available',
    icon: 'user-check',
    href: '/tools/username',
    category: 'player',
    phase: 2,
  },
  {
    id: 'skincustom',
    title: 'Skin Gallery',
    description: 'Browse and customize Minecraft skins',
    icon: 'images',
    href: '/tools/skincustom',
    category: 'player',
    phase: 2,
  },
  {
    id: 'playerstats',
    title: 'Player Stats',
    description: 'View Minecraft player statistics',
    icon: 'chart-bar',
    href: '/tools/playerstats',
    category: 'player',
    phase: 2,
  },
  {
    id: 'uuidhistory',
    title: 'UUID History',
    description: 'View username change history',
    icon: 'clock-rotate-left',
    href: '/tools/uuidhistory',
    category: 'player',
    phase: 2,
  },
  {
    id: 'potions',
    title: 'Potion Calculator',
    description: 'Calculate potion effects and durations',
    icon: 'flask',
    href: '/tools/potions',
    category: 'utility',
    phase: 2,
  },
  {
    id: 'crafting',
    title: 'Crafting Reference',
    description: 'View crafting recipes and block IDs',
    icon: 'table-cells',
    href: '/tools/crafting',
    category: 'utility',
    phase: 2,
  },
  {
    id: 'loot',
    title: 'Loot Simulator',
    description: 'Simulate mob drops and loot tables',
    icon: 'treasure-chest',
    href: '/tools/loot',
    category: 'utility',
    phase: 2,
  },
  {
    id: 'seedfinder',
    title: 'Seed Analyzer',
    description: 'Analyze Minecraft seeds and find structures',
    icon: 'seedling',
    href: '/tools/seedfinder',
    category: 'world',
    phase: 2,
  },
  {
    id: 'biome',
    title: 'Biome Finder',
    description: 'Find biomes at specific coordinates',
    icon: 'tree',
    href: '/tools/biome',
    category: 'world',
    phase: 2,
  },
  {
    id: 'coords',
    title: 'Coordinate Converter',
    description: 'Convert between Overworld, Nether, and End coordinates',
    icon: 'arrows-left-right',
    href: '/tools/coords',
    category: 'world',
    phase: 2,
  },
  {
    id: 'seedmap',
    title: 'Seed Map Viewer',
    description: 'Generate map visualization from seed',
    icon: 'map',
    href: '/tools/seedmap',
    category: 'world',
    phase: 2,
  },
  {
    id: 'randomskin',
    title: 'Random Skin',
    description: 'Generate random Minecraft skins',
    icon: 'shuffle',
    href: '/tools/randomskin',
    category: 'community',
    phase: 2,
  },
  {
    id: 'randomserver',
    title: 'Random Server',
    description: 'Discover random Minecraft servers',
    icon: 'dice',
    href: '/tools/randomserver',
    category: 'community',
    phase: 2,
  },
  {
    id: 'motdgallery',
    title: 'MOTD Gallery',
    description: 'Browse popular server MOTDs',
    icon: 'photos',
    href: '/tools/motdgallery',
    category: 'community',
    phase: 2,
  },
  {
    id: 'news',
    title: 'Minecraft News',
    description: 'Latest Minecraft updates and patch notes',
    icon: 'newspaper',
    href: '/tools/news',
    category: 'community',
    phase: 2,
  },
];

export const getToolsByCategory = (category: string) => {
  return tools.filter((tool) => tool.category === category);
};

export const getToolsByPhase = (phase: number) => {
  return tools.filter((tool) => tool.phase === phase);
};

export const getToolById = (id: string) => {
  return tools.find((tool) => tool.id === id);
};
